# Generated by Django 3.2.4 on 2021-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210613_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lash_length_and_curl',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='lash_line_length',
            field=models.CharField(max_length=254),
        ),
    ]
